include: configs/config_base.yaml

# BnB-specific overrides
tuning:
  backend: bnb         # BitsAndBytes backend

train:
  bf16: false          # BitsAndBytes works best with fp16
  fp16: true
  output_dir: outputs/run-bnb
