include: configs/config_base.yaml

# Unsloth-specific overrides
tuning:
  backend: unsloth     # Unsloth backend
  lora:
    alpha: 32          # Unsloth prefers alpha = r

train:
  bf16: true           # Unsloth works better with bfloat16
  fp16: false
  eval_steps: 1        # More frequent evaluation for Unsloth
  output_dir: outputs/run-unsloth
